#!/bin/bash

# ================================================================
#  _______    _______     ____    _______    _______    __    ___
# |__   __|  |   ____|   / _  \  |__   __|  |   ____|  |  \   | |
#    | |     |  |__     | | | |     | |     |  |__     |   \  | |
#    | |     |   __|    | | | |     | |     |   __|    | |\ \ | |
#    | |     |  |___    | |_| |     | |     |  |___    | | \ \| |
#    |_|     |______|    \____/     |_|     |______|   |_|  \___|
# ----------------------------------------------------------------
# Author: Manuel Teodoro Tenango
# Email: teotenn@proton.me
# Repo: https://github.com/teotenn/dotfiles_wayland
# License: GPL-3
#
# My personal control script for xrandr options in eridani
#
#
# ================================================================

slimb_full="Slimbook Full"
slimb_scaled="Slimbook Scaled in"
dual_full="Dual screen full"
dual_scaled="Dual screen scaled"

chosen=$(printf "%s\n%s\n%s\n%s" \
		"$dual_scaled" "$slimb_scaled" "$dual_full" "$dual_scaled" \
		| rofi -theme ~/Code/dot_tt/rofi/transparent1.rasi \
		       -dmenu -selected-row 0)

case $chosen in
    "$dual_scaled")
	xrandr --output eDP-1 --mode 2880x1800 --scale 0.5x0.5 --rate 90.00 \
	       --output HDMI-1 --mode 1920x1080 --right-of eDP-1
	;;

    "$slimb_scaled")
	xrandr --output eDP-1 --mode 2880x1800 --scale 0.5x0.5 --rate 90.00
	;;

    "$dual_full")
	xrandr --output eDP-1 --mode 2880x1800 --scale 1x1 --rate 90.00 \
	       --output HDMI-1 --mode 1920x1080 --right-of eDP-1
	;;

    "$dual_scaled")
	xrandr --output eDP-1 --mode 2880x1800 --scale 1x1 --rate 90.00
	;;
esac
